### ISSUE TITLE
Async API

### ISSUE THREAD

**Issue by karshan** [karshan/money-scraper#1]
Scraping is a slow process (it is common for it to take > 30 seconds). The API should be async:

/\<bank\>/initiateScrape :: Creds -> OperationId
/\<bank\>/poll :: OperationId -> Success TxnData | Error | OperationInProgress

Another option is to use webhooks. Then we would have

/\<bank\>/initiateScrape :: Creds -> WebhookUrl -> Success | Error

**Comment by ssharma1081** [comment]
Fixed by 5e0836832f5eede1e44afe43c546ba66ce7ac8cb
